### ISSUE TITLE
LRC-6 (Block Reward Interim Restructure)

### ISSUE THREAD

**Issue by Haafingar** [loki-project/loki-improvement-proposals#20]
Continuing on the lengthy discussion in #10, Pulse (PoS) will require a restrucutre of the Loki block reward system.

The Loki Foundation is set up to ensure the continued development of the Loki project, including Session, Lokinet, and the Loki blockchain. It is a registered charity in Australia, and its members are comprised of trusted community members and prominent individuals in the decentralised technology space (see https://loki.foundation/about-loki-foundation/).

Over the last two years, we’ve committed to being as transparent, productive and pragmatic as possible. I believe that the majority of the Loki community sees this, and understands that running Loki at this scale and speed is a costly exercise. With almost 30 full time staff, Loki is a substantial operation, achieving incredible results in delivering truly private secure communications and transaction tools, and educating the public on the importance of privacy and the benefits of using our free, open source technology.

The Loki Foundation is looking to the future, and we believe that in order to improve our likelihood of medium to long term success, we need to propose a change the the block reward structure to allow the foundation to retain its ability to raise more funds. The Foundation can easily sustain itself with its current liquid assets for over 2 years, and the Loki it currently has can be sold in a private investor round to significantly extend the runway, but without that being replenished over a reasonable amount of time, it is going to be more difficult in the following years for the Foundation to sustain itself off grants and donations alone, even with a very large user base. 

Further to this, the miners of Loki are sucking up a large percentage of the block reward whilst providing very little security (due to checkpointing). With Pulse (PoS) on the horizon, it makes sense to me that we should cut down the miners rewards while we’re here as well.

In LRC 3, I proposed to drop the overall block reward to 20 Loki per block, and have a 95/5% split between SNs and LF once miners are out of the picture.

Today I wish to present an idea which has been debated by the LF board. In summary, the board is presenting:

At the upcoming fork in approximately 4 weeks, we change the block reward to 25.00 down from 28.00 (just a fixed amount, no longer dropping over time), with block reward allocations of:
- 66% for Service Nodes
- 10% for Loki Foundation
- 24% for Mining

At the fork that implements Pulse (which will likely be the following one), we switch to block rewards of 21.00 with allocations of:
- 90% for Service Nodes
- 10% for Loki Foundation

which will then be fixed indefinitely (i.e. forever, or until a future SN vote to change them). This means that for each of these two changes, the SNs receive an additional 2.25 and 2.4 Loki per block respectively. Increasing the final reward from 20 to 21 per block will allow the previous modelling around Service Node rewards in LRC-3 to remain in tact if a 10% LF reward is agreed upon and implemented.

Changes like this are not to be taken lightly so we would love to hear the thoughts of the community before moving ahead. This does somewhat change the social contract around the Loki ecosystem, although the community has come to a consensus on sensible changes to the block reward before, so I remain hopeful that this is something users, stakers, and supporters of Loki can get behind.

NOTE: This topic is seperate to #18 - I think some points have been raised there that may require some creative thinking and design in regards to exit incentivisiation, so I would encourage those interested in that particular issue to participate in that discussion there.

**Comment by SomethingGettingWrong** [comment]
Would it be possible to take a portion of the 90 percent and dedicate it to exit nodes?  

For example if 80 percent go to all of the super nodes.. but then 10 percent gets rotateed every block to exit nodes incentivizing service nodes to want to be an exit node.. while also retaining 90 percent toward service nodes. 

For example roughly using a small number for 

If you have 1000 service nodes  and 300 of them are exit nodes. 

Then 1000 share the 80 percent of emission and the other 10 percent goes to the 300 exit nodes  and the foundation gets 10 percent. 

This will create incentive to run an exit node where there isnt one at no extra cost.

**Comment by Prophet-26** [comment]
Can you provide the community with some figures that substantiate your claim? Some questions that will help alleviate some concerns are:

- How much Loki does the foundation currently have?
- Considering the current expenditure rate, what must the price of Loki be to sustain the foundation based on the existing 5% reward. 

If the 10% figure was derived from the current Loki price then an assumption is made that Loki at double the price will be enough to sustain the foundation at 5% block reward. 

With over 2 years worth of seed funding plus the $loki the foundation currently own, the chances are very high that Loki will achieve the price needed to attain sustainability when those funds are due to expire. I understand that is speculation but considering the scope of what Session and the other products aim to achieve, I believe this to be a fair assumption to make. 

I propose that this block reward increase is premature based on the amount of reserve funds and what can be achieved during that time. I believe implementing this increase introduces the potential for the foundation excessively funded.

**Comment by necro-nemesis** [comment]
I'm fine with the short term proposal. wrt the secondary Pulse implementation split I'd like to see more analysis on exits and any other potential requirements for node specialization that may require a different reward model prior to finalizing this aspect.

**Comment by Prophet-26** [comment]
It's also important to consider that the implementation of Pulse will significantly increase the rewards the foundation receive from the service nodes they operate, which is always close to 10% of all service nodes on the network. In essence the foundation will receive close to 19% of the block reward after the implementation of pulse.

**Comment by Lucifer1903** [comment]
I agree with @necro-nemesis

**Comment by lungdoge** [comment]
> It's also important to consider that the implementation of Pulse will significantly increase the rewards the foundation receive from the service nodes they operate, which is always close to 10% of all service nodes on the network. In essence the foundation will receive close to 19% of the block reward after the implementation of pulse.

It's worth noting that the foundation has never hit the 10% self-imposed network limit to date. And with the ambitions of future funding rounds and the continual growth of the network, it may be some time until it does.

**Comment by yidakee** [comment]
PoW becomes redundant with checkpointing, and Pulse cannot arrive too soon. Why drop to 24%? Why not drop to 5%, or even 1%, or some other arbitrarily low value right now and start mimic'ing Pulse? All mining does right now is consume electricity and sell pressure on the market, most from Chinese datacenters with virtually no running costs. Long are the days of altruistic or HOLD mining. The intention here is to create more favourable market conditions, so lets not be shy about this.

Regarding Foundation funds, given the current Loki team track record for transparency, diligence, and accountability, I have no issues with 10%, even if spot price quadruples. The Foundation is not so public facing in daily ops as the core Loki team, but of course they go hand in hand. A healthy cashflow flow will benefit all Loki holders with a solid Foundation that doesn't suffer from funding anxiety. 

Finally, and as mentioned by others, exit nodes need some thought, however since there are more unknowns than certainties at this point, regarding specs and ISP acceptance, I think we should debate this when we get there. % for exist would come out of global SN fee IMHO

**Comment by Lucifer1903** [comment]
I would be okay with temporarily increasing the foundation percentage to 15% or 20% and reducing the mining reward by a larger amount as long as it goes back down to 10% at the hardfork that implements pulse.

**Comment by dwarner5522** [comment]
I like it.  I think with all the development going on with the various platforms it's time the LF gets a boost like this.  I think 10% of the block reward is more than fair.

**Comment by oddslol** [comment]
I strongly disagree with raising the reward for the foundation. For a start, the foundation already run service nodes with the Loki that they already have. @Prophet-26 suggested they own close to 10% of the current service nodes - This means even under a 95/5% split proposal for Pulse they would earn 9.5% more rewards on top of the 5% governance which they are *already* getting.

They have enough runway for two years without evening touching their Loki stack (private sale to investors). After those two years they'll have even more Loki than they have now (5% governance + service node payments) and they should have been working on increasing the scope and success of Loki (e.g. the value of that Loki they are holding will have gone up).

Asking for another 5% block reward on top of getting almost 15% is at best completely unncessary at this moment in time (they have two years runway still) and at worst looks like a complete cash grab.

FWIW - I've been in Loki since the private sale, run a small number of service nodes and was made a "Community God" back in the early days of the project.

**Comment by Skelaton4** [comment]
The Foundation is required by **law** to act on the best interest of the project. 

Without the development team, all of our investments will be worth next to nothing. Although two years of runway seems like a lot, not many want to invest in a project that is on life support with it's funds running low.  I think making this move now will put Loki in a position of strength moving forward with any future potential investors.

**Comment by oddslol** [comment]
What's the difference between 2 years of run way and having 10% Loki per block (+ however much from service nodes) or 2 years of run way and having 5% per block (+ however much from service nodes)?

If service nodes are already providing the foundation with roughly another 10% of each block (as they own 10% of all nodes and the reward will change towards 95/5 split) then the difference between the foundation getting 15% or 20% of each block is 33%. You think that the this extra 33% more Loki they'll get will be the difference between the project dying or not in the future? I think if they'd run out of money at 5% reward, then they'll run out of money at 10% reward.

Not to mention the fact that a lot of other crypto projects would be flabergasted at the fact that an organisation is taking 15% of their block reward already, we now want to increase it to near 20%.

You say the foundation should act in the best interest of the project. So how about we demand from them an economic proposal / writeup that categorically shows that this increase in block reward is **necessary** rather than just allow them to take it for fear of rocking the boat.

**Comment by Skelaton4** [comment]
> What's the difference between 2 years of run way and having 10% Loki per block (+ however much from service nodes) or 2 years of run way and having 5% per block (+ however much from service nodes)?

Good Question. More details would be good to have. 
> 
> If service nodes are already providing the foundation with roughly another 10% of each block (as they own 10% of all nodes and the reward will change towards 95/5 split) then the difference between the foundation getting 15% or 20% of each block is 33%. You think that the this extra 33% more Loki they'll get will be the difference between the project dying or not in the future? I think if they'd run out of money at 5% reward, then they'll run out of money at 10% reward.

The extra 33% could make the difference between getting a large investor or not. Impossible to know, one way, or the other. 

> 
> Not to mention the fact that a lot of other crypto projects would be flabergasted at the fact that an organisation is taking 15% of their block reward already, we now want to increase it to near 20%.

Some projects raised 30-100 million but have no dev fee, this one raised 9 million and will have one. Not sure we should care what other Crypto projects/organizations think about the way the project was funded. 
> 
> You say the foundation should act in the best interest of the project. So how about we demand from them an economic proposal / writeup that categorically shows that this increase in block reward is **necessary** rather than just allow them to take it for fear of rocking the boat.

The Foundation is **Required** (by AU Law )to act in the best interest of the Loki Project. I agree a more detailed write up about what the difference in the fee structure will provide would be beneficial to the discussion. 

--Nothing that I have seen in my 2 years of following this projects makes me feel like this is a cash grab. The team has proven ethical and dedicated to producing their vision, this request doesn't change my view.

**Comment by jagerman** [comment]
> exit nodes need some thought

See [LRC-5](https://github.com/loki-project/loki-improvement-proposals/issues/18) for some discussion on that.  @necro-nemesis is pushing for (and I agree with) a market-based approach rather than a block reward approach to funding exits.

**Comment by Lucifer1903** [comment]
Decreased emissions benefits every holder.
Increased Service Node reward from ~14 to ~16 per block.
Increased Foundation funding.
Decreased miner reward as they are not contributing much now that checkpointing has been implemented. 
Looks like everyone wins except miners who are leaving soon anyway. 

I would also like to quote Kraig from Telegram "Without the LF and the team, this project would be worth didlely squat. I don't think the community squabbling over 5% is worth it. I would rather the LF have it then miners.."

**Comment by William-E-Coyote** [comment]
I generally agree with the proposal. 

I particularly like the reduced emission to miners. This should drive the price upwards and reduce everyone's fears for a while. 

Some other ideas, Selling on the open market drives price down. If the LF is selling to VC to raise money off the market, then I completely agree to the proposal. If the LF is selling on the market, it will drive the price down.  If the project is strong then this is not a problem and the market will absorb the tokens, if the market is weak, this will continue to drive the market into a failure spiral. No funds and low price means the LF has to sell more LOKI to make the monthly rent, continuing to drive down the price. 

If the LF sells the increased LOKI immediately, the market will absorb the coins and the foundation could build a reserve of funding outside of LOKI and even crypto. They could begin to purchase other assets, like cash, stock, or their building, in an effort to reduce future expenses and potential reducing the market. 

To completely agree with the proposal, I would like the LF to announce how they plan on spending the increased reward. I would much prefer selling on the open market immediately, or reserving the reward for VC then just saving the reward for a rainy day. If you spending LOKI after the coin shows signs of weakness, you are further destroying the remaining value of the project.

**Comment by CryptoFirefly** [comment]
I would not change the block reward twice, as we have so many moving parameters that drive the earnings for a node.

Total No. of nodes, What happens to other nodes like Deregs, Decomm, IP changes, Loki's price in USD... and changing % for block split. So suggest to reduce the block rewards 25 Loki right away without any curve and keep it at 25.00.

My Suggestion is

At the upcoming fork in approximately 4 weeks, change the block reward to 25.00:
70% for Service Nodes
10% for Loki Foundation
20% for Mining* + Txn Fees _(As aim is to remove mining off the next fork anyways)_

* Miners also get Txn fees right now, so dropping another 4% would give a bit more for the node ops and drive up our node count even more. We should be 50% lock-up with higher rewards.

At the fork that implements Pulse keep block reward as 25.00 **:
80% for Service Nodes + Txn Fees
10% for Loki Foundation
10% Build Bucket of Funds to support launch of Exits or other SNApps

At fork when Exits go Live
90% Shared by Service Nodes / Exits + Txn Fees
10% for Loki Foundation

** Do not change the emission as we'll need enough Loki in the blocks to keep for Exit Nodes or some other major launch. Also that 10% from Pulse launch onwards, would help build some funds to support exits launch. This 10% fund should not be used by LF, but given out as initial incentives for Exits in a decentralized & objective way and a portion could also be spent on marketing, exchange deposits etc, to sync with when we go live with exits.

**Comment by lewisphil** [comment]
Is the LF currently maximizing the Loki rewards at their disposal right now?  
It’s mentioned above that the LF isn’t at the 10% limit right now.  Why not?
The LF could, and IMO should operate this bank of Loki responsibly and maximize their returns utilizing every opportunity before asking for more.

My suggestion is:  
1.  Always operate max nodes (10%)
2.  Open partial nodes at market value fees (as the market allows, full nodes if this doesn’t work) to capture more rewards
3. Unlock monthly and capture the “extra” from decreasing requirements 

Maximize the rewards before asking for more.

If there’s a reason this isn’t happening, or this is already happening, then I fully support 10% going to the LF before some miners.

But I would like an expiration on the 10%.  How about 4 hard forks then it’s mandatory 5%?

**Comment by Lucifer1903** [comment]
I've already posted above but I just want to mention something else that I remember someone saying a couple of months ago that I think has relevance here.

For most cryptocurrency projects it is difficult to change the emissions schedule because the most important thing is the social contract because the goal is to get people using the Cryptocurrency as money.
However, for Loki while the social contract is still important the health and usage of the network is more important. The value of loki comes from the network and the premium service.
I personally think keeping the network healthy means keeping it decentralised, not screwing over the operators that run the network and making sure the foundation has enough funding to continue development at a pace that continues to provide value.

**Comment by cryptonote-social** [comment]
I can't support the proposal. First my disclaimer: I am both a miner and staker of Loki, though I get most of my rewards from staking.

For the short term issue of bumping foundation rewards to 10% from 5% (which BTW you should make more clear in the proposal), you should provide a more detailed financial breakdown of the foundation. For example clearly you have a lot of Loki coins from the premine and ongoing block rewards which are presumably being staked. How exactly is that doing, and why isn't it enough? I might be open to the proposal but not without a lot more detail.

Regarding the longer term proposal of completely abandoning PoW, I don't feel PoS has been sufficiently proven out in practice. I see Loki's choice of roughly 50/50 split between PoW and PoS as a safe and pragmatic choice it shouldn't abandon in the near future. Let some other big coin demonstrate that pure PoS is a safe choice (such as Ethereum). Until then, Loki shouldn't be the trailblazer. Too much risk for a coin that's ostensibly about providing privacy-preserving services to the masses.

**Comment by Haafingar** [comment]
Sorry for the delay in response, I was offline over the weekend (probably not going to drop an LRC 12 hours before I go out of phone range again haha)

To clear up the details of why we're proposing an increase from 10% from 5%, the maths say that if we sell all of our current holdings at the end of the year in our planned second VC round, it will take years to build up enough funds from the governance reward to be able to continue staking at a decent level again. If we are granted 10% by the network, we will be able to re-stake much more quickly (as the effect is compounding) and prepare for future rounds.

There are no absolute figures here, as the ability for us to raise enough funds to justify selling any Loki at all is price dependent. I have no attitude to sell any Loki to anyone at a price below 1 USD. Further, I wish to reiterate the Loki Foundation's position that **we have not and will not liquidate our Loki assets on market.** We only plan on selling Loki in VC deals. The difference of 5% to 10% is quite substantial for the Foundation if we choose to sell the majority of our Loki assets to VCs within the next 12-14 months. It means we can maintain our ability to earn Loki over time through staking much more rapidly then would otherwise be the case.

At this moment, we have about 4.6 million Loki, (only ~10% of the circulating supply), and we will need to hold a minimum for 800k Loki to maintain our market liquidity service for the project and to keep some staking alive so we can use those service nodes to do our own network analytics and testing, as well as retaining some income. Going from 5% to 10% makes this much less difficult, as we will have an extra 250k Loki to use by that time from the extra boost, and means we can go from a balance of 800k Loki back to ~4m Loki in mid 2023 instead of 2025, which postures us for further funding much more quickly if it is required.

In terms of the discussion here, I particularity like Lucifer's summary. 

> Decreased emissions benefits every holder.
>Increased Service Node reward from ~14 to ~16 per block.
>Increased Foundation funding.
>Decreased miner reward as they are not contributing much now that checkpointing has been implemented.
>Looks like everyone wins except miners who are leaving soon anyway.

Yidakee said something about funding anxiety. Funding anxiety is a problem that will never go away, this request is an attempt to mitigate some of that concern, and it would really help us manage this project for the community in the best way that we can. **In submitting this proposal, I do so because I believe it serves the interest of every person that owns Loki or cares about our mission.** Some of you think I'm wrong, and that is criticism I'm willing to accept. I stand behind this request and I hope you can see how it will serve all of us in the long run.

If this proposal is rejected, it will not be the end of Loki, this certainly doesn't change our short-term or mid-term standing to a large degree. I don't buy the argument that you can't change the social contract because people won't use it as money. We all collectively decide what the social contract is, and what I think matters more than an immutable emissions scheme (which, if you recall, has already been changed several times, all of which with less emission) is that the community behind the currency is strong, and that the team that ultimately facilitates its existence and its use is perceived to be competent, well resourced, and successful.

Regarding PoS/PoW, the decision to move to PoS is now well behind this community, its something that was discussed and has been agreed upon. Even now, miners provide almost no security to this network thanks to check-pointing. Service Nodes make Loki what it is, and they form a fundamental part of our security model, so transitioning to PoS is the obvious next step.

**Comment by Skelaton4** [comment]
Ultimately, it boils down to this. 

Will your current and future holdings of Loki be worth more or less with the Foundation getting a bigger block reward? 

Will the health and longevity of the project improve with the Foundation getting a bigger block reward? 

- I support the changes.

**Comment by necro-nemesis** [comment]
We still need to consider the desire/requirement to restructure block reward to cover exits. That or look at an open market model or some blended funding approach to launch them before being able to apportion the future split. At present I see a correlation between funding them and the ability to have greater direction on exits; but the juice may not be worth the squeeze to control this external facing portion of the Lokinet. It may also prove to be impossible to scale to meet demands using internal funding. A free market model may be a more suitable option while appreciating that this requires relinquishing a fair degree of control over the distribution of exits. Regardless if they are to be funded that funding should be considered in this discussion when it comes to future reward split.

**Comment by William-E-Coyote** [comment]
Haafingar, thank you for your detailed response. I fully agree with the proposal.

**Comment by kimjangsoo** [comment]
I disagree

There is still funds to develop for two years.

Selling to VC does not guarantee that the LOKI price will rise.

There is not enough evidence to increase the Foundation's compensation per block to 10%.

Q1. What is the price of LOKI for sale on VC?

Q2.What is the benefit to holders when selling to VC?

**Comment by Lucifer1903** [comment]
@kimjangsoo  selling to VC is no a strategy to make the price rise it's to continue guaranteed funding for development. 

A1. @Haafingar said there wouldn't be sold for less than $1 per loki.

A2. A VC sale benefits holders because the projet continues to be funded. What more directly benefits holders is the block reward restructure, decreased coin inflation and less coins going to miners who probably have to sell them to pay for electricity. Going ahead with this proposal will reduce the mining reward from ~12.6 to 6 meaning less selling pressure which should translate into higher price.

**Comment by yidakee** [comment]
VC also establishes potential great developments in the social backend, lets not forget that.

**Comment by VINCEG-afk** [comment]
If the foundation commits to not selling bellow 1 usd and promise to decrease the dev tax back to 5% once target amount is raised then I have no issues with this proposal.

**Comment by Lucifer1903** [comment]
I would prefer to keep foundation at 10%. 

An extra 5% for service nodes isn't going to make much difference but I think it would make a big difference towards development and marketing. 

Maybe at a later date it could be split 7.5% Foundation, 2.5% Loki Funding System, 90% service nodes.

**Comment by Haafingar** [comment]
Our intentions regarding the VC round are to sell it at above $1, otherwise we may not carry on the round until such a price is possible. We also intend to ensure that lock up periods are in place for these deals. However, I do not wish to make and hard and fast commitments right now, as we only have so much bargaining power with the VCs, and we need to have some wiggle room in our strategy.

@necro-nemesis Unfortunately time constraints prevent this discussion for the time being. I am leaning towards market based incentives or even sponsored exits as the solution to this problem. Carving out a chunk of the block reward is going to create some perverse incentives for underperformance. In any case I think it is out of scope for now. 

I will leave this issue open for another 48 hours before summarising and concluding this discussion.

**Comment by William-E-Coyote** [comment]
I appreciate the discussion and I agree with the proposal. I expect to have many more discussions about shifting the reward structure and other changes that are necessary for the success of the project. I recognize that currently, we are still a new project and that we are overcoming many problems that were foreseen and we kinda have to act rather quickly to overcome those obstacles.  Furthermore, right now, pretty much everyone is positive and willing to work together. We are not suffering from political infighting. As this project grows and rises in price, we may not be able to simply work together for the good of the project. 

Hopefully we can learn from this discussion and begin to formalize a way to make a changes to the reward structure. 

Developing this system would be a decent sized project in itself. I can only begin to imagine how many working parts there are to the LOKI project and how they each would be appropriately valued. I do think that beginning to develop a formal system for reward changes now would help solve problems much easier, many years form now.

**Comment by necro-nemesis** [comment]
@Haafingar I understand but rather than leaving it in the realm of unfunded by block reward yet undetermined I'd rather forge ahead with structuring exits on an internally unfunded basis. I'm going under the assumption that Exits are a strategic benefit to the platform which in my personal view is an assumption based on what they collectively bring to the platform. Without internal funding I see the requirement for concessions to the current concept of full SN carrying out this task. At present I believe it's looking at the EN structure as a separate entity from the SN otherwise there's limited (no) appeal to operate one. How this shift effects interest based on Sybil attack to Exits has to be judged but it seems we are at a point of compromise if we aren't posturing to ensure the existing nodes are compensated and regulated internally to cover this capability.

**Comment by Lucifer1903** [comment]
I agree with @William-E-Coyote "I do think that beginning to develop a formal system for reward changes now would help solve problems much easier, many years form now".

**Comment by SomethingGettingWrong** [comment]
if you have 5 percent of the nodes now and Node emission doubles dont you get double the emission from your nodes to begin with?  basicly you get 4x the emssion once you go from 5 pecent at 55 percent to 10 percent at 90 percent etc. 

So your going from x to 4x amounts from 5 percent to 10 percent. ... why not 7.5 percent insstead of 10 percent?

**Comment by Lucifer1903** [comment]
@SomethingGettingWrong 
I just want to point out that the node emissions isn't going to double under this proposal. If it passes the service node reward will first go from ~14 to 16 (a ~14% increase from current reward) and then go 18.9 (a 35% increase from current reward)

**Comment by Haafingar** [comment]
@necro-nemesis I don't see regular SNs running exits. It just won't work, as you've identified. They will be separate machines that may or may not be tied to an existing SN, but the uptime of the exit wont affect the base SN reward of the main node or node network.

After opening this discussion 11 days ago, the discussion has been good, some questions have been asked, many of which have been addressed, and some ancillary issues have been raised and discussed. I asses the majority consensus to be moving in support of this proposal. This will be taken to the LF board for a final sign off before the developers implement it's effects for the next hard fork!
